apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api-dev
  namespace: argocd
  labels:
    environment: dev
    project: central-platform
spec:
  project: dev
  source:
    repoURL: https://github.com/Avenis3010/ignite-solutions.git
    targetRevision: dev
    path: backend-services/users-api/backend-api
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false   # namespace is pre-created by k8s/dev/namespace.yaml
