name: Database Migration Prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.DATABASE_PROD_ROLE_ARN }}
        aws-region: ap-south-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name central-platform-prod-eks --region ap-south-1

    - name: Apply prod configmap
      run: |
        kubectl create namespace prod --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f migrations/prod/configmap.yaml

    - name: Delete previous migration job if exists
      run: kubectl delete job mysql-migration -n prod --ignore-not-found=true

    - name: Run migration job
      run: |
        kubectl apply -f migrations/prod/migration-job.yaml
        kubectl wait --for=condition=complete job/mysql-migration -n prod --timeout=300s

    - name: Print migration logs
      run: kubectl logs job/mysql-migration -n prod
